export const enum UTileType {
    MAINTILE='MAINTILE',
    SOCIALTILE='SOCIALTILE',
    LISTTILE='LISTTILE',
}

export const enum UFrameType {
    FULLFRAME='FULLFRAME',
    HALFWIDTHFRAMEWITHROW='HALFWIDTHFRAMEWITHROW',
    HALFWIDTHFRAMEWITHCOL='HALFWIDTHFRAMEWITHCOL',
    HALFHEIGHTFRAMEWITHROW='HALFHEIGHTFRAMEWITHROW',
    HALFHEIGHTFRAMEWITHCOL='HALFHEIGHTFRAMEWITHCOL',
}
